/**
 * Golden-file tests for the poetry markdown pipeline.
 * Each .input.md fixture is parsed through the same remark/rehype
 * plugins used in production; the output is compared to
 * the .expected.html generated by the real PHP parser.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync } from 'fs';
import { resolve, join } from 'path';
import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkGfm from 'remark-gfm';
import remarkRehype from 'remark-rehype';
import rehypeStringify from 'rehype-stringify';
import remarkStanza from '../src/lib/markdown/remark-stanza.ts';
import rehypeReveal from '../src/lib/markdown/rehype-reveal.ts';

const FIXTURES = resolve(__dirname, 'fixtures');

async function processMarkdown(input: string): Promise<string> {
  const result = await unified()
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkStanza)
    .use(remarkRehype, { allowDangerousHtml: true })
    .use(rehypeReveal)
    .use(rehypeStringify, { allowDangerousHtml: true })
    .process(input);
  return String(result);
}

/**
 * Normalise HTML for comparison:
 * - Unify <br /> vs <br> (PHP XHTML vs HTML5)
 * - Decode &quot; (PHP htmlspecialchars encodes, rehype doesn't)
 * - Strip newlines between closing/opening tags (PHP concatenates inline)
 */
function normalise(html: string): string {
  return html
    .replace(/\r\n/g, '\n')
    .replace(/[ \t]+\n/g, '\n')
    .replace(/&quot;/g, '"')
    .replace(/<br\s*\/?>/g, '<br>')
    .replace(/<br>\n/g, '<br>')
    .replace(/>\n</g, '><')
    .trim();
}

const inputFiles = readdirSync(FIXTURES).filter((f) => f.endsWith('.input.md'));

describe('poetry markdown pipeline vs PHP golden files', () => {
  for (const inputFile of inputFiles) {
    const name = inputFile.replace('.input.md', '');
    const expectedFile = join(FIXTURES, `${name}.expected.html`);

    it(`${name}: matches PHP golden output`, async () => {
      const input = readFileSync(join(FIXTURES, inputFile), 'utf8');
      const expected = readFileSync(expectedFile, 'utf8');

      const actual = await processMarkdown(input);

      expect(normalise(actual)).toBe(normalise(expected));
    });
  }
});
